#!/bin/bash
#This script is used to install and configure networknode
#Author: kkk
#Date:- 27-10-2014

#RUN THIS SCRIPT IN BACKGROUND by using '&'

# Preapre the kernel to use neutron
sed -i '/Functions /a \
net.ipv4.ip_forward=1 \
net.ipv4.conf.all.rp_filter=0 \
net.ipv4.conf.default.rp_filter=0' /etc/sysctl.conf

#To update kernel settings
sysctl -p

#Install neutworking Components
apt-get install neutron-plugin-ml2 neutron-plugin-openvswitch-agent \
  neutron-l3-agent neutron-dhcp-agent -y

#Configure network components
#Layer-3 Agent

sed -i '/DEFAULT/ a \
interface_driver = neutron.agent.linux.interface.OVSInterfaceDriver \
use_namespaces = True \
verbose = True ' /etc/neutron/l3_agent.ini

#DHCP agent
sed -i '/DEFAULT/a \
interface_driver = neutron.agent.linux.interface.OVSInterfaceDriver \
dhcp_driver = neutron.agent.linux.dhcp.Dnsmasq \
use_namespaces = True \
dnsmasq_config_file = /etc/neutron/dnsmasq-neutron.conf ' /etc/neutron/dhcp_agent.ini
#Create and edit the /etc/neutron/dnsmasq-neutron.conf file
touch /etc/neutron/dnsmasq-neutron.conf
echo "dhcp-option-force=26,1454" > /etc/neutron/dnsmasq-neutron.conf
killall dnsmasq

#Configure Metadata agent
sed -i '/DEFAULT/a \
auth_url = http://controller:5000/v2.0 \
auth_region = regionOne \
admin_tenant_name = service \
admin_user = neutron \
admin_password = NEUTRON_PASS \
nova_metadata_ip = controller \
metadata_proxy_shared_secret = METADATA_SECRET \
verbose = True \
' /etc/neutron/metadata_agent.ini

#Metadata secret 
sed -i '/security_group_api/a \
service_neutron_metadata_proxy = true \
neutron_metadata_proxy_shared_secret = novaneutron ' /etc/nova/nova.conf
service nova-api restart

#configure ML2 Plugin
sed -i '/#enable_ipset/a \
\[ovs\] \
local_ip = 127.0.0.1 \
tunnel_type = gre \
enable_tunneling = True ' /etc/neutron/plugins/ml2/ml2_conf.ini

#Configure OpenvSwitch(OVS) service
service openvswitch-switch restart
ovs-vsctl add-br br-int
ovs-vsctl add-br br-ex
ovs-vsctl add-port br-ex eth0
dhclient br-ex
ifconfig eth0 0

#edit the network interface file according to OVS
#sed -i '/auto eth0/a \
#face eth0 inet manual\
#up ip link set dev $IFACE up \
#down ip link set dev $IFACE down \
#br-ex
#auto br-ex \
#iface br-ex inet dhcp \
#' /etc/network/interfaces





# Restart the Networking services
service neutron-plugin-openvswitch-agent restart
service neutron-l3-agent restart
service neutron-dhcp-agent restart
service neutron-metadata-agent restart
neutron agent-list
