#!/bin/bash
#This script will edit the nova.conf file and palce the parameters ,so that neutron  work with nova

# settings for nova to use neutron
sed '/enabled_apis/ a \
#neutron settings for nova \
network_api_class = nova.network.neutronv2.api.API \
neutron_url = http://controller:9696 \
neutron_auth_strategy = keystone \
neutron_admin_tenant_name = service \
neutron_admin_username = neutron \
neutron_admin_password = neutron \
neutron_admin_auth_url = http://controller:35357/v2.0 \
linuxnet_interface_driver = nova.network.linux_net.LinuxOVSInterfaceDriver \
firewall_driver = nova.virt.firewall.NoopFirewallDriver \
security_group_api = neutron \

' /etc/nova.conf

#retstart services
service nova-api restart
service nova-scheduler restart
service nova-conductor restart
service neutron-server restart

