#!/bin/bash
#This script is used to install & configure compute node

#PREREQUISITES FOR A COMPUTE NODE
# To setup ip in hosts file
#	sed '/localhost/ i <place your ip> controller' /etc/hosts >/etc/hosts
	sed -i '/localhost/ i 192.168.1.5 computenode' /etc/hosts
# update the package repository
	apt-get update
#Install and configure NTP server
	apt-get install ntp -y
	service ntp restart
	cp /etc/ntp.conf /etc/ntp.conf.bkp
	sed -i 's/server/#server/g' /etc/ntp.conf
	echo "server controller.local" >> /etc/ntp.conf
	service ntp start
#install python-software-properties
	apt-get install python-software-properties -y
#To enable the openstack repository
	#touch  /etc/apt/sources.list.d/ubuntu-cloud-archive-juno-trusty.list
	echo "deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/juno main" > /etc/apt/sources.list.d/ubuntu-cloud-archive-juno-trusty.list
#Ubuntu Cloud archive repository keyring
	apt-get install ubuntu-cloud-keyring
	#apt-get update && apt-get dist-upgrade
	apt-get update
#Install rabbitmq server
	apt-get install rabbitmq-server -y


##Installing COMPUTE Packages
apt-get install nova-compute sysfsutils
#rabbit_settings
sed -i "/DEFAULT/ a \
verbose = True \
rpc_backend = rabbit \
rabbit_host = controller \
rabbit_password = guest \
auth_strategy = keystone\
my_ip = 192.168.1.193 <computenode IP>\
vnc_enabled = True \
vncserver_listen = 0.0.0.0 \
vncserver_proxyclient_address = <computeNode IP> \
novncproxy_base_url = http://controller:6080/vnc_auto.html \
network_api_class = nova.network.neutronv2.api.API \
security_group_api = neutron \
linuxnet_interface_driver = nova.network.linux_net.LinuxOVSInterfaceDriver \
firewall_driver = nova.virt.firewall.NoopFirewallDriver" /etc/nova/nova.conf


sed -i "/firewall_driver/ a \
\[keystone_authtoken\]
auth_uri = http://controller:5000/v2.0 \
identity_uri = http://controller:35357 \
admin_tenant_name = service \
admin_user = nova \
admin_password = nova" /etc/nova/nova.conf

sed -i "/admin_password/ a \
\[neutron\] \
auth_strategy = keystone \
admin_auth_url = http://controller:35357/v2.0 \
admin_tenant_name = service \
admin_username = neutron \
admin_password = neutron
url = http://controller:9696 " /etc/nova/nova.conf

sed -i "/url/ a \
\[glance\] \
host=controller" /etc/nova/nova.conf

sed -i 's/kvm/qemu/g' /etc/nova/nova-compute.conf
service nova-compute restart
rm -f /var/lib/nova/nova.sqlite


######################
##Configure Compute node for networking
#####################

# Preapre the kernel to use neutron
sed -i '/Functions/ a \
net.ipv4.ip_forward=1 \
net.ipv4.conf.all.rp_filter=0 \
net.ipv4.conf.default.rp_filter=0' /etc/sysctl.conf

#To update kernel settings
sysctl -p

apt-get install neutron-plugin-ml2 neutron-plugin-openvswitch-agent

##
sed -i "/DEFAULT/ a \
verbose = True \
rpc_backend = rabbit \
rabbit_host = controller \
rabbit_password = guest \
auth_strategy = keystone \
core_plugin = ml2 \
service_plugins = router \
allow_overlapping_ips = True " /etc/neutron/neutron.conf

sed -i "/firewall_driver/ a \
\[keystone_authtoken\]
auth_uri = http://controller:5000/v2.0 \
identity_uri = http://controller:35357 \
admin_tenant_name = service \
admin_user = neutron \
admin_password = neutron" /etc/neutron/neutron.conf

sed -i "/ / a \
[\ml2\] \
type_drivers = flat,gre \
tenant_network_types = gre \
mechanism_drivers = openvswitch "  /etc/neutron/plugins/ml2/ml2_conf.ini

sed -i "// a \
[\ml2_type_gre\] \
tunnel_id_ranges = 1:1000 "  /etc/neutron/plugins/ml2/ml2_conf.ini

sed -i "// a \
[\securitygroup\] \
enable_security_group = True \
enable_ipset = True \
firewall_driver = neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver" /etc/neutron/plugins/ml2/ml2_conf.ini

sed -i "// a \
[\ovs\]
local_ip = INSTANCE_TUNNELS_INTERFACE_IP_ADDRESS
enable_tunneling = True \
[\agent\]
tunnel_types = gre" /etc/neutron/plugins/ml2/ml2_conf.ini



service nova-compute restart
service neutron-plugin-openvswitch-agent restart
service openvswitch-switch restart