#!/bin/bash
#This script is used to prepare & configure nova  services
#Author:kiku
#Date:-29/10/2014

#Create a mysql database
#database configuration
mysql -u root -ptoor << EODs
CREATE DATABASE nova;
GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost' \
  IDENTIFIED BY 'nova';
GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%' \
  IDENTIFIED BY 'nova';
EODs

#nova user
keystone user-create --name nova --pass nova

#Link the nova user to the service tenant and admin role:
keystone user-role-add --user nova --tenant service --role admin

#create nova service
keystone service-create --name nova --type compute \
  --description "OpenStack Compute"

#Compute service endpoint
 keystone endpoint-create \
  --service-id $(keystone service-list | awk '/ compute / {print $2}') \
  --publicurl http://controller:8774/v2/%\(tenant_id\)s \
  --internalurl http://controller:8774/v2/%\(tenant_id\)s \
  --adminurl http://controller:8774/v2/%\(tenant_id\)s \
  --region regionOne

#Install nova Packages
apt-get install nova-api nova-cert nova-conductor nova-consoleauth \
  nova-novncproxy nova-scheduler python-novaclient -y

#nova DB setup in nova.conf
#sed -i 's/connection=/#connection' /etc/nova/nova.conf
sed -i '/enabled_apis/ a \
\[database\] \
connection=mysql:\/\/nova:nova@controller\/nova' /etc/nova/nova.conf

#rabbit_settings
sed -i '/DEFAULT/ a \
rpc_backend = rabbit \
rabbit_host = controller \
rabbit_password = guest \
my_ip = 127.0.0.1 \
vncserver_listen = 127.0.0.1 \
verbose = true \
vncserver_proxyclient_address = 127.0.0.1 \
#Neutron for nova \
ec2_private_dns_show_ip=True \
api_paste_config=\/etc\/nova\/api-paste.ini \
enabled_apis=ec2,osapi_compute,metadata \
network_api_class = nova.network.neutronv2.api.API \
security_group_api = neutron \
linuxnet_interface_driver = nova.network.linux_net.LinuxOVSInterfaceDriver\
firewall_driver = nova.virt.firewall.NoopFirewallDriver' /etc/nova/nova.conf

#keystone_authtoken
sed -i '/connection/ a \
\[keystone_authtoken\] \
auth_uri = http:\/\/controller:5000\/v2.0 \
#identity_uri = http:\/\/controller:35357 \
auth_host = controller \
auth_port = 35357 \
auth_protocol = http \
admin_tenant_name = service \
admin_user = nova \
admin_password = nova ' /etc/nova/nova.conf

#Glance 
sed -i '/connection=/ a \ 
\[glance\] \
host = controller' /etc/nova/nova.conf

sed -i '/admin_password =/ a \
\[neutron\] \
url=http:\/\/controller:9696 \
auth_strategy=keystone \
admin_auth_url=http:\/\/controller:35357\/v2.0 \
admin_tenant_name=service \
admin_username=neutron \
admin_password=neutron \
service_metadata_proxy=True \
metadata_proxy_shared_secret = METADATA_SECRET' /etc/nova/nova.conf

#remove sqlitedb
rm -f /var/lib/nova/nova.sqlite

#Sync mysql database
nova-manage db sync

#ALL service restart
service nova-api restart
service nova-cert restart
service nova-consoleauth restart
service nova-scheduler restart
service nova-conductor restart
service nova-novncproxy restart
#Test service
nova service-list
nova image-list

