#!/bin/bash
#This script is used for keystone installation and basic configuration
#Author : kiku
#Dependencies:
# 	edit /etc/hosts file and place <replace with ur ip> <controller>
#	
# Total Changes "3"
#database configuration

mysql -u root -ptoor << EODs
CREATE DATABASE keystone;
GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' \
  IDENTIFIED BY 'keystone';
GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' \
  IDENTIFIED BY 'keystone';
EODs

# keystone Installation
	apt-get install keystone python-keystoneclient -y

# Backup config file
	cp /etc/keystone/keystone.conf /etc/keystone/keystone.conf.old
#Enable Token
	sed -i 's/#admin_token/admin_token /g' /etc/keystone/keystone.conf 

#Change Database Path
	sed -i 's/connection=sqlite:\/\/\/\/var\/lib\/keystone\/keystone.db/connection=mysql:\/\/keystone:keystone@controller\/keystone /g' /etc/keystone/keystone.conf

#Enable log Verbose
	sed -i 's/#verbose=false/verbose=true /g' /etc/keystone/keystone.conf

#Sync keystone database
	keystone-manage db_sync
#Remove Old sqllite db
rm -f /var/lib/keystone/keystone.db
service keystone restart
